name: Reusable workflow

on:
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        id: step_one
        env:
         React_App_Prod: true
        run: |
          echo "the variable $React_App_Prod"
  Second:
    runs-on: ubuntu-latest
    steps:
      - name: Set second value
        id: step_two
        run: |
          echo "React_App_Production=false" >> $GITHUB_ENV
          echo "React_App_Dev=fdsjjj" >> $GITHUB_ENV
          cat .env
