name: Reusable workflow

on:
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        id: step_one
        env:
         React_App_Prod: true
        run: |
          echo "the variable $React_App_Prod"
  Second:
    runs-on: ubuntu-latest
    steps:
      - name: Set second value
        id: step_two
        run: |
          echo "React_App_Production=false" > .env
          echo "React_App_Dev=fdsjjj" >> .env
          cat .env
  Third:
    runs-on: ubuntu-latest
    steps:
      - uses: AutoModality/action-clean@v1
      - uses: actions/checkout@v2
      - name: set node
        uses: actions/setup-node@v2
        with: 
          node-version: 18
      - name: npm install
        run: npm install
      - name: zip artifact
        run: zip -r my-artifact.zip file.txt newfile.txt package.json
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: my-artifact.zip
      # - name: download artifact
      #   uses: actions/download-artifact@v2
      #   with: 
      #     name: my-artifact
      #     path: my-artifact.zip
