name: Reusable workflow

on:
  workflow_dispatch:
  
env:
  REACT_APP_PROD: true
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        id: step_one
        run: |
          echo "the variable $env.REACT_APP_PROD"
