name: Calculate Min Max Duration

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install request python
        run: pip install requests
          
      - name: Run script
        run: |
          python find_max_min.py
